apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-service
  labels:
    app: news-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: news-service
  template:
    metadata:
      labels:
        app: news-service
    spec:
      containers:
        - name: news-service
          image: ghcr.io/opendonationassistant/oda-news-service:11
          ports:
            - containerPort: 8080
          env:
            - name: JDBC_URL
              value: jdbc:postgresql://postgres/postgres?currentSchema=news
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: MICRONAUT_ENVIRONMENTS
              value: standalone
      imagePullSecrets:
        - name: regcred
